### ISSUE TITLE
Documentation: Where is .env file located?

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/photoprism_ynh#32]
I need to change photoprisim's storage from /home to /var/Multimedia. This used to be done via config. I still see an example config in /var/www/photoprism/live but no current config

**Comment by Limezy** [comment]
Yes, the config has now changed to be through the .env file. I will have to remove the config file in a future release.
The env is located in `/var/www/photoprism`. Once changed, you can run `sudo yunohost service restart photoprism`
For questions such as that one, I prefer that [you ask them here instead](https://forum.yunohost.org/t/photoprism-an-ai-powered-photos-app-for-the-decentralized-web/20963/14) rather than opening issues
Thanks !
